// The gRPC face of the OTel Lite system of record: the same ls/cat browse
// the CLI uses, the alert rules with their current state, and a live feed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: otellite/v1/sor.proto

package sorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertState int32

const (
	AlertState_ALERT_STATE_UNSPECIFIED AlertState = 0
	AlertState_ALERT_STATE_FIRED       AlertState = 1
	AlertState_ALERT_STATE_RESOLVED    AlertState = 2
)

// Enum value maps for AlertState.
var (
	AlertState_name = map[int32]string{
		0: "ALERT_STATE_UNSPECIFIED",
		1: "ALERT_STATE_FIRED",
		2: "ALERT_STATE_RESOLVED",
	}
	AlertState_value = map[string]int32{
		"ALERT_STATE_UNSPECIFIED": 0,
		"ALERT_STATE_FIRED":       1,
		"ALERT_STATE_RESOLVED":    2,
	}
)

func (x AlertState) Enum() *AlertState {
	p := new(AlertState)
	*p = x
	return p
}

func (x AlertState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertState) Descriptor() protoreflect.EnumDescriptor {
	return file_otellite_v1_sor_proto_enumTypes[0].Descriptor()
}

func (AlertState) Type() protoreflect.EnumType {
	return &file_otellite_v1_sor_proto_enumTypes[0]
}

func (x AlertState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertState.Descriptor instead.
func (AlertState) EnumDescriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{0}
}

type LsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsRequest) Reset() {
	*x = LsRequest{}
	mi := &file_otellite_v1_sor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsRequest) ProtoMessage() {}

func (x *LsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsRequest.ProtoReflect.Descriptor instead.
func (*LsRequest) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{0}
}

func (x *LsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dir           bool                   `protobuf:"varint,2,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_otellite_v1_sor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetDir() bool {
	if x != nil {
		return x.Dir
	}
	return false
}

type LsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsResponse) Reset() {
	*x = LsResponse{}
	mi := &file_otellite_v1_sor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsResponse) ProtoMessage() {}

func (x *LsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsResponse.ProtoReflect.Descriptor instead.
func (*LsResponse) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{2}
}

func (x *LsResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatRequest) Reset() {
	*x = CatRequest{}
	mi := &file_otellite_v1_sor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatRequest) ProtoMessage() {}

func (x *CatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatRequest.ProtoReflect.Descriptor instead.
func (*CatRequest) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{3}
}

func (x *CatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_otellite_v1_sor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{4}
}

func (x *Sample) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Sample) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Sample) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type CatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*Sample              `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatResponse) Reset() {
	*x = CatResponse{}
	mi := &file_otellite_v1_sor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatResponse) ProtoMessage() {}

func (x *CatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatResponse.ProtoReflect.Descriptor instead.
func (*CatResponse) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{5}
}

func (x *CatResponse) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type RulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RulesRequest) Reset() {
	*x = RulesRequest{}
	mi := &file_otellite_v1_sor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesRequest) ProtoMessage() {}

func (x *RulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesRequest.ProtoReflect.Descriptor instead.
func (*RulesRequest) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{6}
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"` // one of > >= < <=
	Threshold     float64                `protobuf:"fixed64,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	HoldFor       *durationpb.Duration   `protobuf:"bytes,4,opt,name=hold_for,json=holdFor,proto3" json:"hold_for,omitempty"`
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_otellite_v1_sor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{7}
}

func (x *Rule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Rule) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Rule) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Rule) GetHoldFor() *durationpb.Duration {
	if x != nil {
		return x.HoldFor
	}
	return nil
}

func (x *Rule) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type RuleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Firing        bool                   `protobuf:"varint,2,opt,name=firing,proto3" json:"firing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleStatus) Reset() {
	*x = RuleStatus{}
	mi := &file_otellite_v1_sor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleStatus) ProtoMessage() {}

func (x *RuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleStatus.ProtoReflect.Descriptor instead.
func (*RuleStatus) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{8}
}

func (x *RuleStatus) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *RuleStatus) GetFiring() bool {
	if x != nil {
		return x.Firing
	}
	return false
}

type RulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RuleStatus          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RulesResponse) Reset() {
	*x = RulesResponse{}
	mi := &file_otellite_v1_sor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesResponse) ProtoMessage() {}

func (x *RulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesResponse.ProtoReflect.Descriptor instead.
func (*RulesResponse) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{9}
}

func (x *RulesResponse) GetRules() []*RuleStatus {
	if x != nil {
		return x.Rules
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_otellite_v1_sor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{10}
}

type AlertEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	State         AlertState             `protobuf:"varint,2,opt,name=state,proto3,enum=otellite.v1.AlertState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertEvent) Reset() {
	*x = AlertEvent{}
	mi := &file_otellite_v1_sor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEvent) ProtoMessage() {}

func (x *AlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEvent.ProtoReflect.Descriptor instead.
func (*AlertEvent) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{11}
}

func (x *AlertEvent) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *AlertEvent) GetState() AlertState {
	if x != nil {
		return x.State
	}
	return AlertState_ALERT_STATE_UNSPECIFIED
}

// WatchResponse is one item on the live feed. Alert is unset for plain samples.
type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Sample        *Sample                `protobuf:"bytes,2,opt,name=sample,proto3" json:"sample,omitempty"`
	Alert         *AlertEvent            `protobuf:"bytes,3,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_otellite_v1_sor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otellite_v1_sor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_otellite_v1_sor_proto_rawDescGZIP(), []int{12}
}

func (x *WatchResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WatchResponse) GetSample() *Sample {
	if x != nil {
		return x.Sample
	}
	return nil
}

func (x *WatchResponse) GetAlert() *AlertEvent {
	if x != nil {
		return x.Alert
	}
	return nil
}

var File_otellite_v1_sor_proto protoreflect.FileDescriptor

const file_otellite_v1_sor_proto_rawDesc = "" +
	"\n" +
	"\x15otellite/v1/sor.proto\x12\votellite.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1f\n" +
	"\tLsRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"-\n" +
	"\x05Entry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\bR\x03dir\":\n" +
	"\n" +
	"LsResponse\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.otellite.v1.EntryR\aentries\" \n" +
	"\n" +
	"CatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"b\n" +
	"\x06Sample\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"<\n" +
	"\vCatResponse\x12-\n" +
	"\asamples\x18\x01 \x03(\v2\x13.otellite.v1.SampleR\asamples\"\x0e\n" +
	"\fRulesRequest\"\x98\x01\n" +
	"\x04Rule\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x01R\tthreshold\x124\n" +
	"\bhold_for\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\aholdFor\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\"K\n" +
	"\n" +
	"RuleStatus\x12%\n" +
	"\x04rule\x18\x01 \x01(\v2\x11.otellite.v1.RuleR\x04rule\x12\x16\n" +
	"\x06firing\x18\x02 \x01(\bR\x06firing\">\n" +
	"\rRulesResponse\x12-\n" +
	"\x05rules\x18\x01 \x03(\v2\x17.otellite.v1.RuleStatusR\x05rules\"\x0e\n" +
	"\fWatchRequest\"b\n" +
	"\n" +
	"AlertEvent\x12%\n" +
	"\x04rule\x18\x01 \x01(\v2\x11.otellite.v1.RuleR\x04rule\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.otellite.v1.AlertStateR\x05state\"\x7f\n" +
	"\rWatchResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12+\n" +
	"\x06sample\x18\x02 \x01(\v2\x13.otellite.v1.SampleR\x06sample\x12-\n" +
	"\x05alert\x18\x03 \x01(\v2\x17.otellite.v1.AlertEventR\x05alert*Z\n" +
	"\n" +
	"AlertState\x12\x1b\n" +
	"\x17ALERT_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ALERT_STATE_FIRED\x10\x01\x12\x18\n" +
	"\x14ALERT_STATE_RESOLVED\x10\x022\xff\x01\n" +
	"\n" +
	"SoRService\x125\n" +
	"\x02Ls\x12\x16.otellite.v1.LsRequest\x1a\x17.otellite.v1.LsResponse\x128\n" +
	"\x03Cat\x12\x17.otellite.v1.CatRequest\x1a\x18.otellite.v1.CatResponse\x12>\n" +
	"\x05Rules\x12\x19.otellite.v1.RulesRequest\x1a\x1a.otellite.v1.RulesResponse\x12@\n" +
	"\x05Watch\x12\x19.otellite.v1.WatchRequest\x1a\x1a.otellite.v1.WatchResponse0\x01BNZLgithub.com/apcandsons/otellite/internal/adapter/grpcapi/pb/otellite/v1;sorv1b\x06proto3"

var (
	file_otellite_v1_sor_proto_rawDescOnce sync.Once
	file_otellite_v1_sor_proto_rawDescData []byte
)

func file_otellite_v1_sor_proto_rawDescGZIP() []byte {
	file_otellite_v1_sor_proto_rawDescOnce.Do(func() {
		file_otellite_v1_sor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_otellite_v1_sor_proto_rawDesc), len(file_otellite_v1_sor_proto_rawDesc)))
	})
	return file_otellite_v1_sor_proto_rawDescData
}

var file_otellite_v1_sor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_otellite_v1_sor_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_otellite_v1_sor_proto_goTypes = []any{
	(AlertState)(0),               // 0: otellite.v1.AlertState
	(*LsRequest)(nil),             // 1: otellite.v1.LsRequest
	(*Entry)(nil),                 // 2: otellite.v1.Entry
	(*LsResponse)(nil),            // 3: otellite.v1.LsResponse
	(*CatRequest)(nil),            // 4: otellite.v1.CatRequest
	(*Sample)(nil),                // 5: otellite.v1.Sample
	(*CatResponse)(nil),           // 6: otellite.v1.CatResponse
	(*RulesRequest)(nil),          // 7: otellite.v1.RulesRequest
	(*Rule)(nil),                  // 8: otellite.v1.Rule
	(*RuleStatus)(nil),            // 9: otellite.v1.RuleStatus
	(*RulesResponse)(nil),         // 10: otellite.v1.RulesResponse
	(*WatchRequest)(nil),          // 11: otellite.v1.WatchRequest
	(*AlertEvent)(nil),            // 12: otellite.v1.AlertEvent
	(*WatchResponse)(nil),         // 13: otellite.v1.WatchResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 15: google.protobuf.Duration
}
var file_otellite_v1_sor_proto_depIdxs = []int32{
	2,  // 0: otellite.v1.LsResponse.entries:type_name -> otellite.v1.Entry
	14, // 1: otellite.v1.Sample.time:type_name -> google.protobuf.Timestamp
	5,  // 2: otellite.v1.CatResponse.samples:type_name -> otellite.v1.Sample
	15, // 3: otellite.v1.Rule.hold_for:type_name -> google.protobuf.Duration
	8,  // 4: otellite.v1.RuleStatus.rule:type_name -> otellite.v1.Rule
	9,  // 5: otellite.v1.RulesResponse.rules:type_name -> otellite.v1.RuleStatus
	8,  // 6: otellite.v1.AlertEvent.rule:type_name -> otellite.v1.Rule
	0,  // 7: otellite.v1.AlertEvent.state:type_name -> otellite.v1.AlertState
	5,  // 8: otellite.v1.WatchResponse.sample:type_name -> otellite.v1.Sample
	12, // 9: otellite.v1.WatchResponse.alert:type_name -> otellite.v1.AlertEvent
	1,  // 10: otellite.v1.SoRService.Ls:input_type -> otellite.v1.LsRequest
	4,  // 11: otellite.v1.SoRService.Cat:input_type -> otellite.v1.CatRequest
	7,  // 12: otellite.v1.SoRService.Rules:input_type -> otellite.v1.RulesRequest
	11, // 13: otellite.v1.SoRService.Watch:input_type -> otellite.v1.WatchRequest
	3,  // 14: otellite.v1.SoRService.Ls:output_type -> otellite.v1.LsResponse
	6,  // 15: otellite.v1.SoRService.Cat:output_type -> otellite.v1.CatResponse
	10, // 16: otellite.v1.SoRService.Rules:output_type -> otellite.v1.RulesResponse
	13, // 17: otellite.v1.SoRService.Watch:output_type -> otellite.v1.WatchResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_otellite_v1_sor_proto_init() }
func file_otellite_v1_sor_proto_init() {
	if File_otellite_v1_sor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_otellite_v1_sor_proto_rawDesc), len(file_otellite_v1_sor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_otellite_v1_sor_proto_goTypes,
		DependencyIndexes: file_otellite_v1_sor_proto_depIdxs,
		EnumInfos:         file_otellite_v1_sor_proto_enumTypes,
		MessageInfos:      file_otellite_v1_sor_proto_msgTypes,
	}.Build()
	File_otellite_v1_sor_proto = out.File
	file_otellite_v1_sor_proto_goTypes = nil
	file_otellite_v1_sor_proto_depIdxs = nil
}
