// The gRPC face of the OTel Lite system of record: the same ls/cat browse
// the CLI uses, the alert rules with their current state, and a live feed.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: otellite/v1/sor.proto

package sorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SoRService_Ls_FullMethodName    = "/otellite.v1.SoRService/Ls"
	SoRService_Cat_FullMethodName   = "/otellite.v1.SoRService/Cat"
	SoRService_Rules_FullMethodName = "/otellite.v1.SoRService/Rules"
	SoRService_Watch_FullMethodName = "/otellite.v1.SoRService/Watch"
)

// SoRServiceClient is the client API for SoRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoRServiceClient interface {
	// Ls lists a directory of the virtual filesystem.
	Ls(ctx context.Context, in *LsRequest, opts ...grpc.CallOption) (*LsResponse, error)
	// Cat returns every sample of one stream, oldest first.
	Cat(ctx context.Context, in *CatRequest, opts ...grpc.CallOption) (*CatResponse, error)
	// Rules returns the configured alert rules and whether each is firing.
	Rules(ctx context.Context, in *RulesRequest, opts ...grpc.CallOption) (*RulesResponse, error)
	// Watch streams samples as they are ingested and alert transitions as
	// they happen. Slow clients miss events rather than slowing ingestion.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type soRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoRServiceClient(cc grpc.ClientConnInterface) SoRServiceClient {
	return &soRServiceClient{cc}
}

func (c *soRServiceClient) Ls(ctx context.Context, in *LsRequest, opts ...grpc.CallOption) (*LsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LsResponse)
	err := c.cc.Invoke(ctx, SoRService_Ls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soRServiceClient) Cat(ctx context.Context, in *CatRequest, opts ...grpc.CallOption) (*CatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatResponse)
	err := c.cc.Invoke(ctx, SoRService_Cat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soRServiceClient) Rules(ctx context.Context, in *RulesRequest, opts ...grpc.CallOption) (*RulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RulesResponse)
	err := c.cc.Invoke(ctx, SoRService_Rules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soRServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SoRService_ServiceDesc.Streams[0], SoRService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SoRService_WatchClient = grpc.ServerStreamingClient[WatchResponse]

// SoRServiceServer is the server API for SoRService service.
// All implementations must embed UnimplementedSoRServiceServer
// for forward compatibility.
type SoRServiceServer interface {
	// Ls lists a directory of the virtual filesystem.
	Ls(context.Context, *LsRequest) (*LsResponse, error)
	// Cat returns every sample of one stream, oldest first.
	Cat(context.Context, *CatRequest) (*CatResponse, error)
	// Rules returns the configured alert rules and whether each is firing.
	Rules(context.Context, *RulesRequest) (*RulesResponse, error)
	// Watch streams samples as they are ingested and alert transitions as
	// they happen. Slow clients miss events rather than slowing ingestion.
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedSoRServiceServer()
}

// UnimplementedSoRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSoRServiceServer struct{}

func (UnimplementedSoRServiceServer) Ls(context.Context, *LsRequest) (*LsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ls not implemented")
}
func (UnimplementedSoRServiceServer) Cat(context.Context, *CatRequest) (*CatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cat not implemented")
}
func (UnimplementedSoRServiceServer) Rules(context.Context, *RulesRequest) (*RulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rules not implemented")
}
func (UnimplementedSoRServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSoRServiceServer) mustEmbedUnimplementedSoRServiceServer() {}
func (UnimplementedSoRServiceServer) testEmbeddedByValue()                    {}

// UnsafeSoRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoRServiceServer will
// result in compilation errors.
type UnsafeSoRServiceServer interface {
	mustEmbedUnimplementedSoRServiceServer()
}

func RegisterSoRServiceServer(s grpc.ServiceRegistrar, srv SoRServiceServer) {
	// If the following call panics, it indicates UnimplementedSoRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SoRService_ServiceDesc, srv)
}

func _SoRService_Ls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoRServiceServer).Ls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SoRService_Ls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoRServiceServer).Ls(ctx, req.(*LsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SoRService_Cat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoRServiceServer).Cat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SoRService_Cat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoRServiceServer).Cat(ctx, req.(*CatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SoRService_Rules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoRServiceServer).Rules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SoRService_Rules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoRServiceServer).Rules(ctx, req.(*RulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SoRService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SoRServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SoRService_WatchServer = grpc.ServerStreamingServer[WatchResponse]

// SoRService_ServiceDesc is the grpc.ServiceDesc for SoRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otellite.v1.SoRService",
	HandlerType: (*SoRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ls",
			Handler:    _SoRService_Ls_Handler,
		},
		{
			MethodName: "Cat",
			Handler:    _SoRService_Cat_Handler,
		},
		{
			MethodName: "Rules",
			Handler:    _SoRService_Rules_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SoRService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "otellite/v1/sor.proto",
}
